#!/usr/bin/env bash
# =============================================================================
# lib/help.sh — `fireplace help` (also: --help, -h, commands, capabilities)
# -----------------------------------------------------------------------------
# Renders a fully-branded Fireplace overview: the block wordmark + a version line
# (like Hermes' startup banner, but ours), a grid of commands with descriptions,
# the agent's capabilities, and — highlighted — the cron/Telegram automation it
# ships with (scheduled scans + custom trading-opportunity alerts).
#
# Pure bash + ANSI on purpose: it runs instantly and identically on the Docker
# and native runtimes, with no container spin-up or venv needed. The native
# Hermes welcome panel (shown when the TUI launches) is generated by Hermes and
# carries its own version; this screen is the Fireplace-branded counterpart.
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=common.sh
. "$HERE/common.sh"

# ----- stdout palette (truecolor on a TTY; plain otherwise) ------------------
if [ -t 1 ]; then
  A='\033[1;38;2;255;106;61m'    # accent (bold #FF6A3D) — headers/commands
  H='\033[1;38;2;255;138;91m'    # bright header
  T='\033[38;2;255;217;199m'     # light body text
  D='\033[38;2;163;130;112m'     # dim/secondary
  F='\033[1;38;2;255;179;71m'    # flame highlight (cron section)
  R='\033[0m'
  G1='\033[1;38;2;255;194;75m'; G2='\033[1;38;2;255;142;43m'; G3='\033[1;38;2;232;73;12m'
else
  A=''; H=''; T=''; D=''; F=''; R=''; G1=''; G2=''; G3=''
fi

RULE="────────────────────────────────────────────────────────────────────────"

# row <command> <description> : color-safe aligned grid row (pad plain ASCII, then
# color). Keep arg 1 ASCII-only — a multibyte char throws off %-Ns byte padding.
row() { printf "  ${A}%-27s${R}${D}%s${R}\n" "$1" "$2"; }
cap() { printf "  %s  ${T}%-12s${R}${D}%s${R}\n" "$1" "$2" "$3"; }

print_logo() {
  printf '\n'
  printf "${G1}%s${R}\n" '███████╗██╗██████╗ ███████╗██████╗ ██╗      █████╗  ██████╗███████╗'
  printf "${G1}%s${R}\n" '██╔════╝██║██╔══██╗██╔════╝██╔══██╗██║     ██╔══██╗██╔════╝██╔════╝'
  printf "${G2}%s${R}\n" '█████╗  ██║██████╔╝█████╗  ██████╔╝██║     ███████║██║     █████╗  '
  printf "${G2}%s${R}\n" '██╔══╝  ██║██╔══██╗██╔══╝  ██╔═══╝ ██║     ██╔══██║██║     ██╔══╝  '
  printf "${G3}%s${R}\n" '██║     ██║██║  ██║███████╗██║     ███████╗██║  ██║╚██████╗███████╗'
  printf "${G3}%s${R}\n" '╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝ ╚═════╝╚══════╝'
}

# ----- header: logo + version line (right below the title, Hermes-style) -----
print_logo
printf "  ${H}Fireplace Agent${R}  ${D}·${R}  ${T}v%s${R}  ${D}·  engine %s  ·  %s runtime${R}\n" \
  "$BUNDLE_VERSION" "$ENGINE_VERSION_REF" "$FP_RUNTIME"
printf "  ${D}Prediction-market research, portfolio & trading copilot — read-only by default.${R}\n"
printf "${D}%s${R}\n" "$RULE"

# ----- commands grid ---------------------------------------------------------
printf "${A}COMMANDS${R}\n"
row "fireplace"            "Start the agent (interactive TUI)"
row "fireplace gateway"   "Telegram bot service — start · stop · logs · status"
row "fireplace cron"      "Schedule jobs & alerts (manage the agent's cron)"
row "fireplace enable-trading"  "Arm order execution (OFF by default)"
row "fireplace disable-trading" "Return to read-only"
row "fireplace doctor"    "Health check — keys, MCP reachability, runtime"
row "fireplace reset"     "Re-run setup (change LLM provider / keys / Telegram)"
row "fireplace update"    "Upgrade Fireplace to the latest version"
row "fireplace uninstall" "Remove Fireplace completely"
row "fireplace help"      "Show this screen"
printf "  ${D}In chat:${R} ${T}/model  /skills  /skin  /compress  /help${R} ${D}— or just ask in plain language.${R}\n"

# ----- capabilities ----------------------------------------------------------
printf "\n${A}CAPABILITIES${R}\n"
cap "📊" "Markets"     "Overviews, order books, candles, trades, open interest, news"
cap "🧠" "Smart money" "Track top wallets and follow their flows in real time"
cap "💼" "Portfolio"   "Positions, P&L, win rate, exposure & concentration"
cap "🛡" "Risk"        "Size trades, read depth/imbalance, set stops & limits"
cap "🔥" "Trading"     "Propose → confirm → execute (opt-in; explicit confirmation)"

# ----- HIGHLIGHTED: cron + Telegram automation -------------------------------
printf "\n${F}⏰ SCHEDULED ALERTS & AUTOMATION${R}  ${D}(cron + Telegram — the agent's killer feature)${R}\n"
printf "  ${T}Tell the agent what to watch; it runs on a schedule and pings your Telegram:${R}\n"
printf "    ${F}•${R} ${T}\"Every 15 min, DM me when smart money opens a >\$10k position.\"${R}\n"
printf "    ${F}•${R} ${T}\"8am daily: send my open positions, P&L, and markets resolving today.\"${R}\n"
printf "    ${F}•${R} ${T}\"Alert me on Telegram if YES on <market> drops below 0.40.\"${R}\n"
printf "    ${F}•${R} ${T}\"Watch new markets matching 'election' and ping me when one lists.\"${R}\n"
printf "  ${D}Manage jobs:${R} ${A}fireplace cron list${R} ${D}· or just describe the alert in chat.${R}\n"
printf "  ${D}Needs:${R} ${T}a Telegram token${R} ${D}(${R}${A}fireplace reset${R}${D}) and the gateway running (${R}${A}fireplace gateway${R}${D}).${R}\n"

printf "${D}%s${R}\n" "$RULE"
printf "  ${D}Read-only by default · run${R} ${A}fireplace enable-trading${R} ${D}to arm execution · ${R}${A}fireplace help${R} ${D}anytime.${R}\n\n"
